export const inventoryCategories = [
  { id: "furniture", name: "Мебель и рабочие зоны", short: "Мебель" },
  { id: "shelter", name: "Шатры и защита", short: "Шатры" },
  { id: "light", name: "Свет", short: "Свет" },
  { id: "climate", name: "Климат и обогрев", short: "Климат" },
  { id: "catering", name: "Быт и кейтеринг", short: "Быт" },
  { id: "office", name: "Офис и печать", short: "Офис" },
  { id: "media", name: "Связь и медиа", short: "Связь" },
  { id: "power", name: "Электрика и зарядка", short: "Электрика" },
  { id: "effects", name: "Спецэффекты", short: "FX" },
  { id: "utility", name: "Хозяйство и транспорт", short: "Хозчасть" },
  { id: "safety", name: "Безопасность и экипировка", short: "Защита" },
];

const categoryName = new Map(inventoryCategories.map((category) => [category.id, category.name]));

const draftStockRanges = {
  furniture: [8, 36],
  shelter: [4, 14],
  light: [12, 42],
  climate: [5, 18],
  catering: [4, 16],
  office: [3, 10],
  media: [5, 30],
  power: [10, 64],
  effects: [2, 7],
  utility: [6, 32],
  safety: [10, 48],
};

function draftStock(id, category) {
  const [min, max] = draftStockRanges[category];
  const hash = [...id].reduce((sum, character, index) => sum + character.charCodeAt(0) * (index + 3), 0);
  return min + (hash % (max - min + 1));
}

function product(id, name, category, options = {}) {
  return {
    id,
    name,
    category,
    categoryName: categoryName.get(category),
    unit: options.unit || "шт.",
    price: options.price ?? null,
    stock: options.stock ?? draftStock(id, category),
    stockEstimated: options.stockEstimated ?? true,
    image: options.image || null,
    published: options.published ?? false,
    featured: options.featured ?? false,
    aliases: options.aliases || [],
  };
}

// Полный рабочий каталог: 89 позиций из списка заказчика + режиссёрское кресло.
// Остатки пока оценочные: после подключения API их заменит Бот-Склад.
// Цена и публичное фото также приходят из Бот-Склада через API.
export const inventoryProducts = [
  product("director-chair", "Кресло режиссёрское", "furniture", {
    price: 650,
    stock: 46,
    image: "assets/catalog/chair-kopatych.webp",
    published: true,
    featured: true,
  }),
  product("bar-stool-high", "Табурет барный высокий", "furniture"),
  product("full-length-mirror", "Ростовое зеркало", "furniture"),
  product("tent-2x2", "Мобильный шатёр 2×2 м", "shelter"),
  product("tent-3x3", "Мобильный шатёр 3×3 м", "shelter"),
  product("tent-3x6", "Мобильный шатёр 3×6 м", "shelter", {
    price: 7800,
    stock: 8,
    image: "assets/catalog/tent-3x6.webp",
    published: true,
    featured: true,
  }),
  product("tent-gutter-3x3", "Водослив для мобильного шатра 3×3 м", "shelter"),
  product("tent-gutter-3x6", "Водослив для мобильного шатра 3×6 м", "shelter"),
  product("hanging-lamp-cable", "Лампа подвесная с проводом", "light"),
  product("led-headlamp", "Налобный светодиодный фонарь", "light"),
  product("desk-lamp", "Настольная лампа", "light"),
  product("car-creeper", "Автомобильный подкат", "utility"),
  product("floor-fan", "Вентилятор напольный", "climate"),
  product("floor-fan-wheels", "Вентилятор напольный на колёсах", "climate"),
  product("portable-air-conditioner", "Мобильный напольный кондиционер", "climate"),
  product("heater-electric-3", "Тепловая электрическая пушка 3 кВт", "climate"),
  product("heater-electric-5", "Тепловая электрическая пушка 5 кВт", "climate"),
  product("heater-electric-9", "Тепловая электрическая пушка 9 кВт", "climate"),
  product("heater-electric-15", "Тепловая электрическая пушка 15 кВт", "climate"),
  product("heater-diesel-20", "Тепловая дизельная пушка 20 кВт", "climate", {
    price: 4200,
    stock: 12,
    image: "assets/catalog/heater-diesel.webp",
    published: true,
    featured: true,
  }),
  product("infrared-heater", "Инфракрасный обогреватель", "climate"),
  product("fridge-50", "Холодильник 50 л", "catering"),
  product("garment-steamer", "Отпариватель на стойке", "catering"),
  product("construction-vacuum", "Строительный пылесос", "utility"),
  product("ice-maker", "Ледогенератор", "catering"),
  product("thermopot-5", "Термопот 3–5 л", "catering"),
  product("thermopot-10", "Термопот 10 л", "catering"),
  product("kettle-18", "Чайник 1,8 л", "catering"),
  product("microwave", "Микроволновая печь", "catering"),
  product("coffee-drip", "Капельная кофемашина", "catering"),
  product("coffee-capsule", "Капсульная кофемашина", "catering"),
  product("water-cooler", "Кулер для воды", "catering"),
  product("ups", "Источник бесперебойного питания", "power", { aliases: ["Бесперебойник", "ИБП"] }),
  product("printer-bw", "Принтер чёрно-белый", "office"),
  product("mfp", "МФУ с принтером и сканером", "office"),
  product("modem-4g", "Интернет-модем 3G/4G", "media"),
  product("garden-blower", "Воздуходувка садовая", "utility"),
  product("speaker-mic", "Акустическая система с микрофоном", "media"),
  product("speaker", "Акустическая система без микрофона", "media"),
  product("tv-50-stand", "Телевизор 50″ со стойкой", "media"),
  product("tv-32", "Телевизор 32″", "media"),
  product("megaphone", "Громкоговоритель", "media"),
  product("intercom-set-8", "Комплект интеркомов, 8 шт.", "media"),
  product("radio-kenwood", "Рация Kenwood", "media", {
    price: 900,
    stock: 78,
    image: "assets/catalog/radio-motorola.webp",
    published: true,
    featured: true,
  }),
  product("storage-case-plastic", "Кофр пластиковый для хранения", "utility"),
  product("usb-charger-10", "USB-зарядная станция на 10 портов", "power"),
  product("usb-charger-40", "USB-зарядная станция на 40 портов", "power"),
  product("usb-charger-100", "USB-зарядная станция на 100 портов", "power"),
  product("hazer-antari-hz", "Хейзер Antari HZ-350 / HZ-400", "effects"),
  product("smoke-machine", "Дым-машина", "effects"),
  product("camera-tv-adapter", "Переходник для ТВ-сигнала камеры", "media"),
  product("cable-reel-50", "Кабельная катушка 50 м", "power"),
  product("cable-reel-30", "Кабельная катушка 20–30 м", "power"),
  product("cable-reel-10", "Кабельная катушка 10 м", "power"),
  product("power-strip-switch", "Сетевой фильтр с кнопкой", "power"),
  product("power-strip", "Сетевой фильтр без кнопки", "power"),
  product("extension-single", "Сетевой удлинитель с одной розеткой", "power"),
  product("camouflage-net", "Маскировочная сеть", "shelter"),
  product("metal-bucket", "Металлическое ведро", "utility"),
  product("shovel-bayonet", "Штыковая лопата", "utility"),
  product("shovel-scoop", "Совковая лопата", "utility"),
  product("shovel-snow", "Снеговая лопата", "utility"),
  product("rake", "Грабли", "utility"),
  product("ice-chopper", "Ледокол", "utility"),
  product("broom-brush", "Метла / щётка", "utility"),
  product("umbrella-camera", "Операторский зонт", "shelter"),
  product("umbrella-actor", "Актёрский зонт", "shelter"),
  product("ladder-transformer", "Лестница-трансформер", "utility"),
  product("clapperboard", "Хлопушка", "utility"),
  product("canister-20", "Канистра 20 л", "utility"),
  product("fitness-mat", "Фитнес-коврик", "furniture"),
  product("strap-rope", "Стропы / верёвка 5–10 м", "utility"),
  product("traffic-cones", "Конусы ограничительные", "safety"),
  product("cone-bars-lights", "Вешки для конусов с лампочками", "safety"),
  product("waders", "Вейдерсы", "safety"),
  product("neoprene-boots", "Неопреновые ботинки", "safety"),
  product("tourist-seat", "Сидушка туристическая", "furniture"),
  product("water-cube", "Куб для воды", "utility"),
  product("fleece-blanket", "Плед флисовый", "furniture"),
  product("ironing-board", "Гладильная доска", "catering"),
  product("cork-board", "Пробковая доска", "office"),
  product("stationery-case", "Канцелярский кофр с наполнением", "office"),
  product("reflective-vest", "Жилет светоотражающий", "safety"),
  product("construction-helmet", "Каска строительная", "safety"),
  product("life-jacket", "Спасательный жилет", "safety"),
  product("gym-mat", "Мат гимнастический", "furniture"),
  product("gym-mat-folding", "Мат гимнастический складной", "furniture"),
  product("tool-set", "Набор инструментов", "utility"),
  product("tablecloth-oxford", "Скатерть на стол, Oxford", "furniture"),
  product("tablecloth-silk", "Скатерть на стол, шёлк", "furniture"),
];

export const inventoryStats = {
  total: inventoryProducts.length,
  categories: inventoryCategories.length,
  withPhoto: inventoryProducts.filter((item) => item.image).length,
  published: inventoryProducts.filter((item) => item.published).length,
};
